### ISSUE TITLE
Needs a release

### ISSUE THREAD

**Issue by dkisselev** [JakeCooper/BattleBirds#1]
if any of you guys still have the repository cloned or have an APK floating around somewhere, upload it as a release. Looking to play some Box Dropping Simulator.

**Comment by ChrisHampu** [comment]
Please see https://github.com/JakeCooper/BattleBirds/releases/tag/v1.0
:)

**Comment by dkisselev** [comment]
derp, apparently I'm blind

**Comment by ChrisHampu** [comment]
I only just uploaded this now haha. I extracted it off my laptop.

**Comment by dkisselev** [comment]
Ohh, github says it was Released in August 2014, I guess that's just the timestamp on the commit source
